// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASkgdoqeN38A7oU78-SkFRP3sCXSI-kT8',
    appId: '1:161782570665:web:7a2db9e8239e03a3acd3b8',
    messagingSenderId: '161782570665',
    projectId: 'thebillingcoach',
    authDomain: 'thebillingcoach.firebaseapp.com',
    storageBucket: 'thebillingcoach.appspot.com',
    measurementId: 'G-VF13JWKLDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIH-djvrwYcSZK7tOX2GzKC70LgkkkxsE',
    appId: '1:161782570665:android:9685ad58c9a472b4acd3b8',
    messagingSenderId: '161782570665',
    projectId: 'thebillingcoach',
    storageBucket: 'thebillingcoach.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcOIynutZgdTvjwallhihQLczXS0lMPqQ',
    appId: '1:161782570665:ios:f168c897495fa246acd3b8',
    messagingSenderId: '161782570665',
    projectId: 'thebillingcoach',
    storageBucket: 'thebillingcoach.appspot.com',
    androidClientId: '161782570665-67h6r8jioo13hou22d47rsf4pcu0qjna.apps.googleusercontent.com',
    iosClientId: '161782570665-06q6ihvn9lno7k556akc3q7iorn50mdk.apps.googleusercontent.com',
    iosBundleId: 'io.developers.webappbillingcoach.webappbillingcoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcOIynutZgdTvjwallhihQLczXS0lMPqQ',
    appId: '1:161782570665:ios:f168c897495fa246acd3b8',
    messagingSenderId: '161782570665',
    projectId: 'thebillingcoach',
    storageBucket: 'thebillingcoach.appspot.com',
    androidClientId: '161782570665-67h6r8jioo13hou22d47rsf4pcu0qjna.apps.googleusercontent.com',
    iosClientId: '161782570665-06q6ihvn9lno7k556akc3q7iorn50mdk.apps.googleusercontent.com',
    iosBundleId: 'io.developers.webappbillingcoach.webappbillingcoach',
  );
}
