//TO DO: add the entitlement ID from the RevenueCat dashboard that is activated upon successful in-app purchase for the duration of the purchase.
const entitlementID = 'premium';
const stockapi = 'm1b2w2yav4.execute-api.ap-south-1.amazonaws.com';
const stockrecapi= "z9u9139hj0.execute-api.ap-south-1.amazonaws.com";
const menuapi= "pm1wx1ol74.execute-api.ap-south-1.amazonaws.com";
const expanseapi= '26nl44iu1f.execute-api.ap-south-1.amazonaws.com';
const expanserecapi= 'satkrrp6hb.execute-api.ap-south-1.amazonaws.com';
const profitapi='wvt4xhiooe.execute-api.ap-south-1.amazonaws.com';
const monthlyprofitapi='ln3iyup34h.execute-api.ap-south-1.amazonaws.com';
const pendingpaymentapi='eai56xqcdf.execute-api.ap-south-1.amazonaws.com';
const paymentrecapi= 'ctxn2q6fr9.execute-api.ap-south-1.amazonaws.com';
const pendingorderapi='f7qdt24oj9.execute-api.ap-south-1.amazonaws.com';
const pendingorderitemapi='x0h4z35thl.execute-api.ap-south-1.amazonaws.com';
const privacypolicyapi= 'rc3vddmed1.execute-api.ap-south-1.amazonaws.com';
const completeorderapi='e6lnuukod3.execute-api.ap-south-1.amazonaws.com';
const completeorderitemapi='kggjrzlb8k.execute-api.ap-south-1.amazonaws.com';//https://kggjrzlb8k.execute-api.ap-south-1.amazonaws.com/CompleteOrderItem
const deletedorderapi='r0ssf2l9u3.execute-api.ap-south-1.amazonaws.com';
const receivedreqapi='ls9zbkjhs4.execute-api.ap-south-1.amazonaws.com';//https://ls9zbkjhs4.execute-api.ap-south-1.amazonaws.com/ReceivedRequest
const sentreqapi= 'vnl0s7n7qa.execute-api.ap-south-1.amazonaws.com';
const rentedapi= 'urj3bixngb.execute-api.ap-south-1.amazonaws.com';
const deletedorderitemapi='8bd2e3a6uf.execute-api.ap-south-1.amazonaws.com';
const customerlistapi='0dccnktwih.execute-api.ap-south-1.amazonaws.com';
const customerrecordapi='wak9e6yil4.execute-api.ap-south-1.amazonaws.com';//https://wak9e6yil4.execute-api.ap-south-1.amazonaws.com/CustomerRecords/customerrecords
const acceptedsupplierapi='icndi8swu3.execute-api.ap-south-1.amazonaws.com';
const supplierapi='rp7l6jjwv9.execute-api.ap-south-1.amazonaws.com';
const chatmessageapi='1sbvstny52.execute-api.ap-south-1.amazonaws.com';//1sbvstny52.execute-api.ap-south-1.amazonaws.com/ChatMessages
const chatitemsapi='1no694umfl.execute-api.ap-south-1.amazonaws.com';//https://1no694umfl.execute-api.ap-south-1.amazonaws.com/ChatItem/chatitems
const notifyapi='47bsmgrrxc.execute-api.ap-south-1.amazonaws.com';
const tokenapi= 'uivuce72ig.execute-api.ap-south-1.amazonaws.com';
const tempitemapi= 'tsa5v77rub.execute-api.ap-south-1.amazonaws.com';
const helpapi= 'brebrf9c5f.execute-api.ap-south-1.amazonaws.com';
const appfeaturesapi= 'kkaf6bhf17.execute-api.ap-south-1.amazonaws.com';
const rkey= '1vk2fhwk6h.execute-api.ap-south-1.amazonaws.com';
const subscript= '5b1jown0c8.execute-api.ap-south-1.amazonaws.com';///AppSubscription/appsubscription
const plansapi= "4dkmgzdo5e.execute-api.ap-south-1.amazonaws.com";
